#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
title: "hunj::devlog"
author:
  name: Hun Jae Lee
  avatar: https://avatars.githubusercontent.com/u/3972717?u=02580682c6f88744673f9cc7c79cc9fa50482826
  title: Software Engineer
  location: Cleveland, OH
  email: hunjael@gmail.com
  uri: https://hunj.dev

# Metatag for SEO
meta_description: "Software development blog"
meta_image_path: "/images/meta.png"

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: admin@hunj.dev
  facebook:
  flickr:
  github: hunj
  instagram:
  linkedin: hunj
  pinterest:
  rss: hunj # just type anything here for a working RSS icon
  twitter: dev_hunj
  stackoverflow: users/4927106/hunj # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
# disqus: hunjgithubio

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-62581922-1

# Enter your Microsoft Clarity web tracking code to activate tracking
microsoft_clarity: 5afr66dx7y

# Your website URL (e.g. http://marifersahin.github.io or http://www.marifersahin.com)
# Used for Sitemap.xml and your RSS feed
url: http://hunj.dev

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
# baseurl: "/"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /blog/:title/

# The release of Jekyll Now that you're using
version: v3.9.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: ''

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jemoji

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - vendor